services:
  postgres:
    container_name: pg-vector
    image: 'ankane/pgvector:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=vector_rh_store'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5400:5432'
    volumes:
      - pg_vector_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin-container
    image: 'dpage/pgadmin4'
    restart: always
    ports:
        - "5055:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@ars.com
        PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
        - postgres
    volumes:
        - pgadmin_vector_data:/var/lib/pgadmin
volumes:
  pg_vector_data:
      driver: local
  pgadmin_vector_data:
      driver: local
